---
- name: Deploy Node.js HTTP server
  hosts: target_server
  become: yes
  tasks:
    - name: Copy Node.js script
      copy:
        src: server.js  # Path to your server.js file
        dest: /etc/server. # Destination path on the remote server
        mode: 0755  # Set appropriate permissions for the file

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Install required npm packages
      npm:
        name: http
        global: yes

    - name: Start Node.js server
      command: node /path/to/destination/server.js
      async: 300
      poll: 0











